<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Core\HEngine.ECS\HEngine.ECS.csproj"/>
        <ProjectReference Include="..\..\Core\HEngine.Scene\HEngine.Scene.csproj"/>
        <ProjectReference Include="..\..\Core\HEngine.Assets\HEngine.Assets.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
        <PackageReference Include="Microsoft.Extensions.Logging"/>
        <PackageReference Include="StbImageSharp"/>
    </ItemGroup>

</Project>
