<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Batches\" />
      <Folder Include="Components\" />
      <Folder Include="Contracts\" />
      <Folder Include="Data\" />
      <Folder Include="Devices\" />
      <Folder Include="Enums\" />
      <Folder Include="Managers\" />
      <Folder Include="Systems\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Core\HEngine.Core\HEngine.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Silk.NET.Core" Version="2.22.0" />
      <PackageReference Include="Silk.NET.Direct3D.Compilers" Version="2.22.0" />
      <PackageReference Include="Silk.NET.Direct3D11" Version="2.22.0" />
      <PackageReference Include="Silk.NET.Direct3D12" Version="2.22.0" />
      <PackageReference Include="Silk.NET.DXGI" Version="2.22.0" />
      <PackageReference Include="Silk.NET.Input" Version="2.22.0" />
      <PackageReference Include="Silk.NET.Windowing" Version="2.22.0" />
    </ItemGroup>

</Project>
