<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <LangVersion>Preview</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ServerGarbageCollection>true</ServerGarbageCollection>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Src\Core\HEngine.ECS\HEngine.ECS.csproj"/>
        <ProjectReference Include="..\..\Src\Core\HEngine.Scene\HEngine.Scene.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet"/>
    </ItemGroup>

</Project>
